name: Run API tests using Docker Compose

on:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Clean dev-cert
      run: dotnet dev-certs https --clean
    - name: Generate dev-cert
      run: dotnet dev-certs https -ep ~/.aspnet/https/aspnetapp.pfx -p Zjyslav19
    - name: set dev-cert permissions
      run: sudo chmod -R a+rwx ~/.aspnet/https
    - name: Docker Compose Action
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "AspWebApiHttpyacTestsDemo.Api/compose.yaml"
        up-flags: "--build --abort-on-container-exit"
